
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class KonversiSuhuFrame extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhuFrame
     */
    public KonversiSuhuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbSkala = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdCelcius = new javax.swing.JRadioButton();
        rdFahrenheit = new javax.swing.JRadioButton();
        rdReamur = new javax.swing.JRadioButton();
        rdKelvin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnKonversi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Nilai Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtSuhu.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSuhuCaretUpdate(evt);
            }
        });
        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuhuKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtSuhu, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Skala Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        cbbSkala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        cbbSkala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbSkalaItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(cbbSkala, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Jenis Konversi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        buttonGroup1.add(rdCelcius);
        rdCelcius.setText("Celcius");
        rdCelcius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdCelciusItemStateChanged(evt);
            }
        });
        jPanel2.add(rdCelcius);

        buttonGroup1.add(rdFahrenheit);
        rdFahrenheit.setText("Fahrenheit");
        rdFahrenheit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdFahrenheitItemStateChanged(evt);
            }
        });
        jPanel2.add(rdFahrenheit);

        buttonGroup1.add(rdReamur);
        rdReamur.setText("Reamur");
        rdReamur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdReamurItemStateChanged(evt);
            }
        });
        jPanel2.add(rdReamur);

        buttonGroup1.add(rdKelvin);
        rdKelvin.setText("Kelvin");
        rdKelvin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdKelvinItemStateChanged(evt);
            }
        });
        jPanel2.add(rdKelvin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtHasil.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(txtHasil, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(btnKonversi, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        Double nilai = getNilai();
        if (nilai == null) {
            JOptionPane.showMessageDialog(this, "nilai suhu masih kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String skala = getSkala();
        String skalaHasil = getSkalaHasil();
        if (skalaHasil == null) {
            JOptionPane.showMessageDialog(this, "Konversi belum dipilih", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        hitungHasil(skalaHasil, skala, nilai);
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            JOptionPane.showMessageDialog(this, "Hanya boleh angka", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtSuhuKeyTyped

    private void txtSuhuCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSuhuCaretUpdate
        hitungHasilOtomatis();
    }//GEN-LAST:event_txtSuhuCaretUpdate

    private void cbbSkalaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbSkalaItemStateChanged
        hitungHasilOtomatis();
    }//GEN-LAST:event_cbbSkalaItemStateChanged

    private void rdCelciusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdCelciusItemStateChanged
        hitungHasilOtomatis();
    }//GEN-LAST:event_rdCelciusItemStateChanged

    private void rdFahrenheitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdFahrenheitItemStateChanged
        hitungHasilOtomatis();
    }//GEN-LAST:event_rdFahrenheitItemStateChanged

    private void rdReamurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdReamurItemStateChanged
        hitungHasilOtomatis();
    }//GEN-LAST:event_rdReamurItemStateChanged

    private void rdKelvinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdKelvinItemStateChanged
        hitungHasilOtomatis();
    }//GEN-LAST:event_rdKelvinItemStateChanged

    private void hitungHasilOtomatis() {
        Double nilai = getNilai();
        if (nilai == null) {
            return;
        }

        String skala = getSkala();
        String skalaHasil = getSkalaHasil();
        if (skalaHasil == null) {
            return;
        }

        hitungHasil(skalaHasil, skala, nilai);
    }

    private Double getNilai() {
        String nilaiString = txtSuhu.getText();
        if (nilaiString.isBlank()) {
            return null;
        }

        return Double.valueOf(nilaiString);
    }

    private String getSkala() {
        return (String) cbbSkala.getSelectedItem();
    }

    private String getSkalaHasil() {
        if (rdCelcius.isSelected()) {
            return "Celcius";
        } else if (rdFahrenheit.isSelected()) {
            return "Fahrenheit";
        } else if (rdReamur.isSelected()) {
            return "Reamur";
        } else if (rdKelvin.isSelected()) {
            return "Kelvin";
        }

        return null;
    }

    private void hitungHasil(String skalaHasil, String skala, Double nilai) {
        Double hasil = null;
        switch (skalaHasil) {
            case "Celcius" -> {
                switch (skala) {
                    case "Celcius" ->
                        hasil = nilai;
                    case "Fahrenheit" ->
                        hasil = (nilai - 32) * 5 / 9;
                    case "Reamur" ->
                        hasil = nilai * 5 / 4;
                    case "Kelvin" ->
                        hasil = nilai - 273.15;
                }
            }
            case "Fahrenheit" -> {
                switch (skala) {
                    case "Celcius" ->
                        hasil = (nilai * 9 / 5) + 32;
                    case "Fahrenheit" ->
                        hasil = nilai;
                    case "Reamur" ->
                        hasil = (nilai * 9 / 4) + 32;
                    case "Kelvin" ->
                        hasil = (nilai - 273.15) * 9 / 5 + 32;
                }
            }
            case "Reamur" -> {
                switch (skala) {
                    case "Celcius" ->
                        hasil = nilai * 4 / 5;
                    case "Fahrenheit" ->
                        hasil = (nilai - 32) * 4 / 9;
                    case "Reamur" ->
                        hasil = nilai;
                    case "Kelvin" ->
                        hasil = (nilai - 273.15) * 4 / 5;
                }
            }
            case "Kelvin" -> {
                switch (skala) {
                    case "Celcius" ->
                        hasil = nilai + 273.15;
                    case "Fahrenheit" ->
                        hasil = (nilai * 9 / 5) + 32 + 273.15;
                    case "Reamur" ->
                        hasil = (nilai * 5 / 4) + 273.15;
                    case "Kelvin" ->
                        hasil = nilai;
                }
            }
        }

        txtHasil.setText(String.valueOf(hasil));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbSkala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdCelcius;
    private javax.swing.JRadioButton rdFahrenheit;
    private javax.swing.JRadioButton rdKelvin;
    private javax.swing.JRadioButton rdReamur;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
